### ISSUE TITLE
what is the default shortcut?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tyru/current-func-info.vim#17]
Please add to readme - hot to call this `nnoremap <C-g>f :echo cfi#format("%s", "")<CR>`

**Comment by tyru** [comment]
No default shortcut.
Because this plugin provides only the way of getting function name in current position.
Please include `cfi#format()` in your `statusline` and so on like this.

```viml
let &statusline .= '%( | %{cfi#format("%s()", "")}%)'
```
