### ISSUE TITLE
Vim died of this plugin

### ISSUE THREAD

**Issue by mingsxs** [tyru/current-func-info.vim#26]
Sometimes this plugin just makes the vim died within my terminal. I was using this plugin on my C sources.

**Comment by mingsxs** [comment]
And when it happens, it will certainly happen when I try to do the same operation at the same place. whenever it is going with MacOS or Linux VIM.

**Comment by tyru** [comment]
You mean Vim died with segfault?
If so, please file this issue on vim/vim after creating minimal code to reproduce.

**Comment by GoldsteinE** [comment]
Vim hangs forever with this plugin in lightline when I write
```c
int main(
```
in C file.

**Comment by GoldsteinE** [comment]
I assume that problem is in this loop: https://github.com/tyru/current-func-info.vim/blob/master/ftplugin/c/cfi.vim#L36

**Comment by GoldsteinE** [comment]
When cursor is here:
```c
int main(
        ^
```
condition
```vim
!empty(synstack(line('.'), col('.')))
```
is true, so it loops forever.

**Comment by mnishz** [comment]
Can anyone try the latest code? This issue should be also fixed. Thank you.

**Comment by tyru** [comment]
If a problem still persists, please reopen this.
